### ISSUE TITLE
how to support claud3.5 sonnet model

### ISSUE THREAD

**Issue by lgb861213** [aws-samples/sample-connector-for-bedrock#17]
I have deploy the application. and I find that it not support claud3.5 sonnet model. and I add the 3.5 model, 

{
  "model_id": "anthropic.claude-3-5-sonnet-20240620-v1:0",
  "anthropic_version": "bedrock-2023-05-31"
}

but when use the 3.5 model, it show the error
{
  "success": false,
  "data": "You do not have permission to access the [claude-3.5-sonnet] model, please contact the administrator."
}

I also restart the docker, but it also show the same error

**Comment by cloudbeer** [comment]
1 Create a model:

Provider: bedrock-converse

```json
{
  "modelId": "anthropic.claude-3-5-sonnet-20240620-v1:0",
  "regions": ["us-east-1", "us-west-2"]
}
```

2 grant this model to group or api-key.

`You do not have permission to access the [claude-3.5-sonnet] model, please contact the administrator.  `  This error means you didn't grant model to the group or api-key.
