### ISSUE TITLE
如何配置默认支持哪个模型

### ISSUE THREAD

**Issue by wangbin-hlj** [aws-samples/sample-connector-for-bedrock#21]
安装了Docker image version 0.0.8，发现使用开源NextChat时，必须自定义模型名称claude-3-sonnet，才能正常工作。之前的版本应该是默认为claude-3-sonnet，如果选择其它openai模型（gpt-3.5-turbo）也会自动使用默认的claude-3-sonnet，是否能保留默认模型的功能？

{
  "success": false,
  "data": "The model [gpt-3.5-turbo] is not found. You may refresh to get new models."
}

**Comment by cloudbeer** [comment]
当前，如果要支持 gpt-3.5-turbo 这个模型，您可以在后台模型管理 那里新建一个模型，名字为 gpt-3.5-turbo。

下一个版本我会加一下默认模型支持。

**Comment by cloudbeer** [comment]
最新发布的 0.0.9 版本 已经支持了默认模型。
当前会默认到 claude-3-sonnet，请保证这个Name 的模型在后台是存在的。
