### ISSUE TITLE
Is BR connector support model isolation?

### ISSUE THREAD

**Issue by ericwang0909** [aws-samples/sample-connector-for-bedrock#5]
For the requirements of our company, different user groups use different models, and these models and data need to be isolated and not shared. Does BR connector have a roadmap to support this feature and ETA? Thanks a lot.

**Comment by cloudbeer** [comment]
Same with: https://github.com/aws-samples/sample-connector-for-bedrock/issues/2

**Comment by cloudbeer** [comment]
Model isolation can now be supported. You can set it up in the management backend /manager.

- You can set up models in group management, and an API Key can belong to a certain group.

- You can also set up models in API Key management.

The models set up in these two ways are additive..
